// AUTO-GENERATED from config/migrate-waves/*.yaml — do not edit by hand.
// Regenerate: python3 scripts/generate_migrate_waves_ts.py

import type { TradeK8sNativeWave } from './tradeK8sNativeCatalogTypes'
import type { DataLayerMigrationPhase } from './dataLayerCatalogTypes'

export const GENERATED_TRADE_K8S_NATIVE_WAVES: TradeK8sNativeWave[] = [
  {
    id: "w0-dev-mock",
    wave: "W0",
    spineIndex: 0,
    label: "Dev IB Mock Gateway — zero live TWS client_id on bifrost-dev",
    repo: "bifrost-trade-socket + bifrost-trade-infra/k8s/overlays/dev",
    verify: "bifrost-dev stack healthy; no eConnect to .30/.33; market pages use redis-replay",
    delivered: "config get_ib_mode + ib.mode:mock; MockIbGateway for ingestor/account/operator ",
  },
  {
    id: "w1-ingress",
    wave: "W1",
    spineIndex: 1,
    label: "Traefik Ingress replaces in-cluster nginx gateway",
    repo: "bifrost-trade-infra/k8s/base + overlays",
    verify: "STG/PROD via Ingress host; SSE buffering off; NodePort bootstrap-only",
    blockedBy: "data-layer-k3s step ⑦ (optional parallel on STG)",
    delivered: "Retired in-cluster nginx Deployment; Traefik IngressRoute + stripPrefix middlewares per API; ",
  },
  {
    id: "w2-ops-k8s-executor",
    wave: "W2",
    spineIndex: 2,
    label: "api-ops executor_mode kubernetes — restore celery-worker Deployment",
    repo: "bifrost-trade-api + bifrost-trade-infra/k8s/overlays",
    verify: "Ops Celery page starts worker pod; api-ops-celery.patch replicas≠0; no subprocess",
    delivered: "KubernetesExecutor (scale/restart Deployments, delete celery pods); ops.executor_mode kubernetes in stg|prod|dev; ",
  },
  {
    id: "w3-manifest-refactor",
    wave: "W3",
    spineIndex: 3,
    label: "Kustomize API component + single image; fix prod config mount alias",
    repo: "bifrost-trade-infra/k8s",
    verify: "kustomize build overlays/stg|prod; 9 domains from one image tag",
  },
  {
    id: "w4-ib-lease-lib",
    wave: "W4",
    spineIndex: 4,
    label: "K8s Lease leader election module in bifrost-trade-socket",
    repo: "bifrost-trade-socket",
    verify: "Unit tests + STG: scale socket to 2 pods — only one holds IB connection",
    delivered: "bifrost_socket.ib.lease — coordination.k8s.io/Lease active-standby library: ",
  },
  {
    id: "w5-ib-statefulset",
    wave: "W5",
    spineIndex: 5,
    label: "IB socket StatefulSet + ServiceAccount/RBAC for Lease",
    repo: "bifrost-trade-infra/k8s/base/socket",
    verify: "kubectl get sts -n bifrost-stg; failover <20s; Error 326 never in logs",
    delivered: "k8s/base/socket: ib-ingestor/ib-account-agent/ib-operator migrated Deployment→StatefulSet ",
  },
  {
    id: "w6-ib-gateway-merge",
    wave: "W6",
    spineIndex: 6,
    label: "Merge ingestor+listener+worker_market → ib-market-gateway (3 gateways total)",
    repo: "bifrost-trade-socket + config",
    verify: "3 client_id per TWS per env; parity smoke on /market/live",
    blockedBy: "w4-ib-lease-lib, w5-ib-statefulset",
    delivered: "W6 gateway merge: ib-ingestor K8s workload → ib-market-gateway StatefulSet ",
  },
  {
    id: "w7-probes-init",
    wave: "W7",
    spineIndex: 7,
    label: "Probes + initContainers — socket/worker wait CNPG/Redis ready",
    repo: "bifrost-trade-infra/k8s/base",
    verify: "rollout restart during data maintenance — no crashloop before data ready",
    delivered: "New scripts/wait_for_data.py (stdlib + yaml, identical in bifrost-trade-socket & ",
  },
  {
    id: "w8-daemon-lease",
    wave: "W8",
    spineIndex: 8,
    label: "Daemon Deployment + Lease — single active auto-trade (R-DV3)",
    repo: "bifrost-trade-worker + k8s/base/worker",
    verify: "2 daemon pods; only Lease holder runs FSM trading loop",
    delivered: "bifrost_worker.daemon.lease — coordination.k8s.io/Lease active-standby for GsTrading ",
  },
  {
    id: "w9-network-policy",
    wave: "W9",
    spineIndex: 9,
    label: "NetworkPolicy — env isolation + IB LAN egress allowlist",
    repo: "bifrost-trade-infra/k8s/base",
    verify: "bifrost-stg cannot reach bifrost-prod redis; socket reaches .30/.33:7496",
    delivered: "k8s/data/redis/network-policies.yaml — 5 ingress NetworkPolicies (redis-live/queue ",
  },
  {
    id: "w10-observability",
    wave: "W10",
    spineIndex: 10,
    label: "IB data-line budget ConfigMap + Celery/Flower metrics",
    repo: "bifrost-trade-infra/k8s + bifrost-trade-worker",
    verify: "Grafana or logs show ib_active_data_lines; Flower or celery_exporter",
    delivered: "k8s/base/observability/ib-data-line-budget.yaml — ConfigMap (account_budget=100, ",
  },
  {
    id: "w11-signoff",
    wave: "W11",
    spineIndex: 11,
    label: "STG Tier A/B + deliver-prod gate — Compose→K3s native sign-off",
    repo: "bifrost-platform + bifrost-trade-infra",
    verify: "make k3s-verify-phase-b-stg-v2; deliver-prod blocked if STG unhealthy",
    delivered: "verify-phase-b-stg-v2.sh — Tier A updated for W5 StatefulSet socket rollouts + W10 Flower ",
  },
]

export const GENERATED_DATA_LAYER_PHASES: DataLayerMigrationPhase[] = [
  {
    id: "data-0-cnpg-operator",
    step: 1,
    spineIndex: 0,
    displayCode: "①",
    label: "Label ubt-k3s-02 postgres-role + deploy CloudNativePG operator + bifrost-postgres cluster (data NS)",
    repo: "bifrost-trade-infra/k8s/data/ + scripts/k3s/install-data-layer-phase0.sh",
    verify: "kubectl get cluster -n data; postgres-role capability ready on ubt-k3s-02",
  },
  {
    id: "data-1-minio-backup",
    step: 2,
    spineIndex: 1,
    displayCode: "②",
    label: "MinIO backup target (nfs-hot) + CNPG barmanObjectStore WAL archive",
    repo: "bifrost-trade-infra/k8s/data/minio/ · nfs-hot StorageClass",
    verify: "CNPG backup status OK; test WAL archive to nfs-hot bucket",
    blockedBy: "data-0-cnpg-operator",
  },
  {
    id: "data-2-stg-cutover",
    step: 3,
    spineIndex: 2,
    displayCode: "③",
    label: "STG cutover — apps connect bifrost-postgres-rw.data.svc + redis-live/queue-stg; remove bifrost-stg in-ns postgres/redis",
    repo: "bifrost-trade-infra/k8s/overlays/stg/",
    verify: "bifrost-stg daemon_control + IB ingestor Stream + deliver-stg smoke pass",
    blockedBy: "data-1-minio-backup",
  },
  {
    id: "data-3-dev-cutover",
    step: 4,
    spineIndex: 3,
    displayCode: "④",
    label: "DEV cutover — bifrost-dev config → data NS endpoints; remove bifrost-dev in-ns postgres/redis",
    repo: "bifrost-trade-infra/k8s/overlays/dev/",
    verify: "Vision V1 gate :30882 + bifrost_dev schema via CNPG",
    blockedBy: "data-2-stg-cutover",
  },
  {
    id: "data-4-prod-pg",
    step: 5,
    spineIndex: 4,
    displayCode: "⑤",
    label: "PROD PG migrate — pg_dump legacy .80 → CNPG bifrost_prod; maintenance window + rollback plan",
    repo: "bifrost-trade-infra/k8s/overlays/prod/config/",
    verify: "make prod-health; monitor daemon_control; D2-prime cutover sign-off",
    blockedBy: "data-3-dev-cutover",
  },
  {
    id: "data-5-redis-split",
    step: 6,
    spineIndex: 5,
    displayCode: "⑥",
    label: "PROD/STG redis-live + redis-queue split (Bitnami HA); Celery → redis-queue only",
    repo: "bifrost-trade-infra/k8s/data/redis/",
    verify: "noeviction on live; Celery bars queue isolated; NetworkPolicy per env",
    blockedBy: "data-4-prod-pg",
  },
  {
    id: "data-6-retire-embedded",
    step: 7,
    spineIndex: 6,
    displayCode: "⑦",
    label: "Retire embedded stateful — remove postgres/redis from bifrost-* base; bare .80 PG standby or offline",
    repo: "bifrost-trade-infra/k8s/base/ · bifrost-platform/config/environments.yaml",
    verify: "data NS only; matrix probes point at cluster endpoints; legacy .80 read-only or decommissioned",
    blockedBy: "data-5-redis-split",
  },
]
