/**
 * Tools registered with reg() in mcp/platform/src/index.ts (the full server).
 * Laptop tools live in registerLocal.ts. Chat approval tools live in registerApprove.ts
 * and must not appear in this list.
 */
export const PLATFORM_STDIO_TOOL_NAMES = [
  'platform_mcp_health',
  'get_connectivity_matrix',
  'verify_payload',
  'verify_mission_snapshot',
  'list_environments',
  'get_ops_context',
  'get_auth_capabilities',
  'get_audit_log',
  'get_cluster_summary',
  'get_cluster_nodes',
  'get_data_freshness',
  'market_data_doctor',
  'market_data_heal',
  'get_postgres_backup_status',
  'trigger_cnpg_backup',
  'repair_cnpg_wal_store',
  'trigger_data_clone',
  'get_data_clone_status',
  'get_gitops_apps',
  'get_delivery_pipelines',
  'get_delivery_run_logs',
  'gitops_sync_app',
  'gitops_rollback_app',
  'start_pipeline_run',
  'delete_pipeline_run',
  'cordon_node',
  'uncordon_node',
  'drain_node',
  'ensure_bifrost_namespaces',
  'rollout_restart_deployment',
  'scale_deployment',
  'delete_pod',
  'wake_compute_node',
  'poweroff_compute_node',
  'get_agent_bridge',
  'get_trust_matrix',
  'get_stg_smoke',
  'get_delivery_revisions',
  'get_commit_lineage',
  'get_checklist_signals',
  'get_code_health',
  'get_telemetry_overview',
  'get_telemetry_alerts',
  'get_telemetry_targets',
  'plan_manifest',
  'create_job_from_cronjob',
  'delete_finished_jobs',
  'run_probe_pod',
  'request_action',
  'get_request',
  'list_requests',
  'wait_for_request',
] as const

export type PlatformStdioToolName = (typeof PLATFORM_STDIO_TOOL_NAMES)[number]
